# Generated by Django 2.1.2 on 2018-10-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("phmi", "0001_add_initial_models")]

    operations = [
        migrations.AlterModelOptions(
            name="caresystem", options={"ordering": ["type__name", "name"]}
        )
    ]
