# Generated by Django 2.1.2 on 2018-10-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0002_auto_20181031_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptype',
            options={'ordering': ['name']},
        ),
    ]
