# Generated by Django 2.1.2 on 2018-10-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("phmi", "0003_auto_20181031_1101")]

    operations = [
        migrations.AlterModelOptions(
            name="caresystem", options={"ordering": ["-type__name", "name"]}
        )
    ]
