# Generated by Django 2.1.2 on 2018-10-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0003_make_password_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='care_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='phmi.CareSystem'),
        ),
    ]
