# Generated by Django 2.1.2 on 2018-11-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0004_auto_20181031_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='care_system',
            field=models.ManyToManyField(blank=True, related_name='orgs', to='phmi.CareSystem'),
        ),
    ]
