# Generated by Django 2.1.2 on 2018-10-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0004_link_user_to_care_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ods_code',
            field=models.TextField(null=True, unique=True),
        ),
    ]
