# Generated by Django 2.1.2 on 2018-10-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0005_nullable_ods_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgtype',
            options={'ordering': ['name']},
        ),
    ]
