# Generated by Django 2.1.2 on 2018-11-07 14:56

from django.db import migrations


def add(apps, schema_editor):
    OrgType = apps.get_model('phmi', 'OrgType')
    Organisation = apps.get_model('phmi', 'Organisation')

    org_type, _ = OrgType.objects.get_or_create(
        name="NHS England"
    )

    Organisation.objects.get_or_create(
        name="NHS England", type=org_type
    )


def remove(*args, **kwarfgs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0006_activity_legaljustification_legalmapping'),
    ]

    operations = [
        migrations.RunPython(
            add, reverse_code=remove
        )
    ]



