# Generated by Django 2.1.2 on 2018-11-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("phmi", "0008_auto_20181107_1652")]

    operations = [
        migrations.RenameField(
            model_name="legalmapping", old_name="organisation", new_name="org_type"
        )
    ]
