# Generated by Django 2.1.2 on 2018-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0009_auto_20181107_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='orgtype',
            name='activities',
            field=models.ManyToManyField(through='phmi.LegalMapping', to='phmi.Activity'),
        ),
    ]
