# Generated by Django 2.1.2 on 2018-11-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("phmi", "0010_auto_20181107_1708")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="care_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="phmi.CareSystem",
            ),
        )
    ]
