# Generated by Django 2.1.2 on 2018-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0012_auto_20181126_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaljustification',
            name='statute',
            field=models.TextField(default=''),
        ),
    ]
