# Generated by Django 2.1.2 on 2018-11-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0013_auto_20181127_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaljustification',
            old_name='activites',
            new_name='activities',
        ),
    ]
