# Generated by Django 2.1.3 on 2018-12-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0017_activitycategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycategory',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phmi.ActivityCategory'),
        ),
    ]
