# Generated by Django 2.1.3 on 2018-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0018_auto_20181204_1604")]

    operations = [
        migrations.AlterModelOptions(
            name="activity", options={"ordering": ["activity_category__name"]}
        ),
        migrations.AlterModelOptions(
            name="activitycategory", options={"ordering": ["name"]}
        ),
        migrations.AlterField(
            model_name="activitycategory",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
