# Generated by Django 2.1.3 on 2018-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0020_auto_20181205_1129")]

    operations = [
        migrations.CreateModel(
            name="Statute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("link", models.URLField()),
            ],
        ),
        migrations.RemoveField(model_name="statutelink", name="justification"),
        migrations.RenameField(
            model_name="legaljustification", old_name="statute", new_name="details"
        ),
        migrations.RemoveField(model_name="legaljustification", name="statute_link"),
        migrations.DeleteModel(name="StatuteLink"),
        migrations.AddField(
            model_name="statute",
            name="justification",
            field=models.ManyToManyField(to="phmi.LegalJustification"),
        ),
    ]
