# Generated by Django 2.1.3 on 2018-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0021_auto_20181205_1140")]

    operations = [
        migrations.RemoveField(model_name="statute", name="justification"),
        migrations.AddField(
            model_name="legaljustification",
            name="statutes",
            field=models.ManyToManyField(to="phmi.Statute"),
        ),
    ]
