# Generated by Django 2.1.3 on 2018-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0023_auto_20181205_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
