# Generated by Django 2.1.3 on 2018-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0024_activitycategory_slug")]

    operations = [
        migrations.AlterModelOptions(name="orgtype", options={"ordering": ["index"]}),
        migrations.AddField(
            model_name="orgtype", name="index", field=models.IntegerField(default=0)
        ),
    ]
