# Generated by Django 2.1.3 on 2018-12-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0025_auto_20181206_1405")]

    operations = [
        migrations.AlterModelOptions(
            name="activitycategory", options={"ordering": ["index"]}
        ),
        migrations.AddField(
            model_name="activitycategory",
            name="index",
            field=models.IntegerField(default=0),
        ),
    ]
