# Generated by Django 2.1.3 on 2018-12-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0026_auto_20181206_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['activity_category__index']},
        ),
    ]
