# Generated by Django 2.1.5 on 2019-01-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phmi', '0029_add-activity-category-group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='phmi.ActivityCategory'),
        ),
    ]
