# Generated by Django 2.1.5 on 2019-01-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("phmi", "0031_add_data_models")]

    operations = [
        migrations.CreateModel(
            name="LawfulBasis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("number", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrgFunction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functions",
                        to="phmi.OrgType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgResponsibility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(default=0)),
                ("name", models.TextField()),
                ("additional_information", models.TextField()),
                ("related_reading", models.TextField()),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="phmi.OrgFunction",
                    ),
                ),
                ("lawful_bases", models.ManyToManyField(to="phmi.LawfulBasis")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="orgfunction", unique_together={("name", "type")}
        ),
    ]
