# Generated by Django 2.1.5 on 2019-01-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("phmi", "0032_add_org_function_and_responsibility")]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("index", models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="BenefitAim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="benefit",
            name="aim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="phmi.BenefitAim"
            ),
        ),
    ]
