# Generated by Django 2.1.5 on 2019-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0034_add_outputs")]

    operations = [
        migrations.AddField(
            model_name="datatype",
            name="activities",
            field=models.ManyToManyField(related_name="data_types", to="phmi.Activity"),
        )
    ]
