# Generated by Django 2.1.5 on 2019-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0036_add_datamap_orgtype")]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("slug", models.SlugField(unique=True, blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="datatype",
            name="services",
            field=models.ManyToManyField(related_name="data_types", to="phmi.Service"),
        ),
    ]
