# Generated by Django 2.1.5 on 2019-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0038_change_legal_justification_org_type_to_m2m")]

    operations = [
        migrations.AlterField(
            model_name="legaljustification",
            name="activities",
            field=models.ManyToManyField(
                related_name="legal_justifications", to="phmi.Activity"
            ),
        ),
        migrations.AlterField(
            model_name="legaljustification",
            name="org_types",
            field=models.ManyToManyField(
                blank=True, related_name="legal_justifications", to="phmi.OrgType"
            ),
        ),
    ]
