# Generated by Django 2.1.5 on 2019-02-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("phmi", "0039_add_related_names")]

    operations = [
        migrations.AddField(
            model_name="activitycategorygroup",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        )
    ]
