# Generated by Django 2.1.5 on 2019-02-07 15:52

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    ActivityCategoryGroup = apps.get_model("phmi", "ActivityCategoryGroup")
    for group in ActivityCategoryGroup.objects.all():
        group.slug = slugify(group.name)[:50]
        group.save()  # trigger the generation of slugs


def remove_slugs(apps, schema_editor):
    ActivityCategoryGroup = apps.get_model("phmi", "ActivityCategoryGroup")
    ActivityCategoryGroup.objects.update(slug="")


class Migration(migrations.Migration):

    dependencies = [("phmi", "0040_add_activity_category_group_slug")]

    operations = [migrations.RunPython(generate_slugs, reverse_code=remove_slugs)]
