# Generated by Django 2.1.5 on 2019-02-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("phmi", "0041_populate_activity_category_group_slugs")]

    operations = [
        migrations.CreateModel(
            name="SubSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(name="legaljustification", options={}),
        migrations.RenameField(
            model_name="lawfulbasis", old_name="name", new_name="description"
        ),
        migrations.RemoveField(model_name="statute", name="link"),
        migrations.AddField(
            model_name="lawfulbasis",
            name="details",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lawfulbasis",
            name="org_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lawful_bases",
                to="phmi.OrgType",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lawfulbasis",
            name="title",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legaljustification",
            name="activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_justifications",
                to="phmi.Activity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legaljustification",
            name="is_specific",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="legaljustification",
            name="lawful_bases",
            field=models.ManyToManyField(
                related_name="legal_justifications", to="phmi.LawfulBasis"
            ),
        ),
        migrations.AddField(
            model_name="legaljustification",
            name="org_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_justifications",
                to="phmi.OrgType",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="statute", name="name", field=models.TextField(unique=True)
        ),
        migrations.RemoveField(model_name="lawfulbasis", name="number"),
        migrations.AddField(
            model_name="lawfulbasis",
            name="subsections",
            field=models.ManyToManyField(
                related_name="lawful_bases", to="phmi.SubSection"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lawfulbasis", unique_together={("org_type", "title", "description")}
        ),
        migrations.RemoveField(model_name="legaljustification", name="activities"),
        migrations.RemoveField(model_name="legaljustification", name="details"),
        migrations.RemoveField(model_name="legaljustification", name="name"),
        migrations.RemoveField(model_name="legaljustification", name="org_types"),
        migrations.RemoveField(model_name="legaljustification", name="statutes"),
        migrations.AlterUniqueTogether(
            name="legaljustification",
            unique_together={("activity", "org_type", "is_specific")},
        ),
        migrations.AddField(
            model_name="subsection",
            name="statute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsections",
                to="phmi.Statute",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subsection", unique_together={("name", "statute")}
        ),
    ]
