---
# This playbook provides basic elements of a server we would like to maintain
- name: generate locale
  become: true
  command: /usr/sbin/locale-gen en_GB.UTF-8

- name: Set locale
  become: true
  command: /usr/sbin/update-locale LANG=en_GB.UTF-8

- name: update apt-cache
  sudo: true
  apt: update_cache=yes

- name: install packages for sysadmin
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - emacs
    - git
    - htop
    - iotop
    - tree
    - ack-grep
    - vim
    - zip
    - screen
    - python-virtualenv
    - virtualenvwrapper
    - python3-dev
    - build-essential
    - circus
    - nginx
    - python3.7
    - python3-pip


- pip:
    name: pipenv
