---
# This playbook provides basic elements of a server we would like to maintain
- name: Ensure locale is available
  locale_gen: name=en_US.UTF-8

- name: update apt-cache
  sudo: true
  apt: update_cache=yes

- name: install packages for sysadmin
  apt: pkg={{ item }} state=installed
  with_items:
    - emacs
    - git
    - htop
    - iotop
    - tree
    - ack-grep
    - vim
    - zip
    - screen
    - python-virtualenv
    - virtualenvwrapper
    - python3-dev
    - build-essential
    - circus
    - nginx
